#!/bin/bash

# 定义要检查的端口号
PORT=8000

# 使用 lsof 查找占用指定端口的进程ID
PID=$(lsof -ti :$PORT)

# 检查是否找到了PID
if [ -z "$PID" ]; then
  echo "没有找到占用端口 $PORT 的进程"
else
  # 杀死占用端口的进程
  kill -9 $PID
  echo "已终止 PID 为 $PID 的进程，它之前占用了端口 $PORT"
fi